version: '3'

services:
  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    restart: "no"
  web:
    build: .
    env_file: .env
    command: bash -c "python manage.py fake_data && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
