version: '3'

services:
  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    restart: "no"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    # use `docker-compose up` via command line or via pycharm
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
